# Generated by Django 4.0.3 on 2022-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topics', models.CharField(max_length=200)),
            ],
        ),
    ]
