# Generated by Django 4.0.3 on 2022-04-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikers_haven', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('f_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hikers_haven.forum')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hikers_haven.post')),
            ],
        ),
    ]
