# Generated by Django 4.0.3 on 2022-04-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikers_haven', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('content', models.CharField(default=None, max_length=2000)),
                ('comm_by', models.ForeignKey(default='user', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comm_on', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hikers_haven.post')),
            ],
        ),
    ]
