# Generated by Django 4.0.3 on 2022-04-26 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikers_haven', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comm_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
