# Generated by Django 4.0.3 on 2022-05-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikers_haven', '0006_alter_comment_comm_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='hikers_haven.forum'),
        ),
    ]
